[build-system]
requires = ["setuptools", "openai"]
build-backend = "setuptools.build_meta"

[project]
name = "ChatGPT cli"
requires-python = ">=3.7"

dependencies = [
    "openai",
    python_version<"3.8"',
]