[build-system]
requires = ["setuptools", "openai"]
build-backend = "setuptools.build_meta"

[project]
name = "chatgpt_cli"
requires-python = ">=3.7"
dynamic = ["version"]

dependencies = [
    "openai",
    'importlib-metadata; python_version<"3.8"',
]